[merchantName]
type = 'String'
isRequired = true
sort = true

[mobileNumber]
type ="String"
isRequired = false
sort = true
encrypted = true

[companyName]
type = "String"
isRequired = false
sort = true

[panNumber]
type = "String"
isRequired = false
sort = true
encrypted = true

[dob]
type = 'String'
isRequired = false
sort = true
encrypted = true

[officialEmailId]
type = "String"
isRequired = false
sort = true
encrypted = true

[merchantID]
type = 'String'
isRequired = true
sort = true
