supportedLanguages = ['english']
useEncryption = true
pathTypes = ['unionFrom', 'unionIn', 'unionFrom']
organisation = 'Pinelabs'
asyncInterfaces = ['socket','messageBus']
serviceName = 'borrowerProfile'
domainName = 'com.Pinelabs.mediaSync'
specversion = '1.0'
host = 'localhost:9092'
clientId ='KunbahProducer'
subscriptionsEnabled = true